# Generated by Django 4.2.16 on 2024-10-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferevent',
            name='transaction_hash',
            field=models.CharField(max_length=66, unique=True),
        ),
    ]
